apiVersion: v1
kind: Service
metadata:
  name: djangoservice
spec:
  selector:
    app: django-web
  ports:
    - protocol: TCP
      port: 8000        # service port
      targetPort: 8000  # pod port
  type: ClusterIP      # default, internal cluster access
