# kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
  - role: control-plane
  - role: worker
    extraMounts:
      - hostPath: /home/sanjeev/Desktop/ecom/venv/E-Commerce-Website/certs
        containerPath: /etc/nginx/certs

      - hostPath: /home/sanjeev/Desktop/ecom/venv/E-Commerce-Website/static
        containerPath: /app/static

      - hostPath: /home/sanjeev/Desktop/ecom/venv/E-Commerce-Website/media
        containerPath: /app/media
