apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    server {
        listen 80;
        server_name _;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl http2;
        server_name _;

        ssl_certificate     /etc/certs/nginx.crt;
        ssl_certificate_key /etc/certs/nginx.key;

        ssl_protocols TLSv1.2 TLSv1.3;

        location /static/ {
            alias /app/static/;
            expires 30d;
            add_header Cache-Control "public, max-age=2592000";
        }

        location /media/ {
            alias /app/media/;
            expires 30d;
            add_header Cache-Control "public, max-age=2592000";
        }

        location / {
            proxy_pass http://djangoservice:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }
       
        client_max_body_size 20M;
    }
